
package org.jboss.as.quickstarts.wshelloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldWS", targetNamespace = "http://wshelloworld.quickstarts.as.jboss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWSI {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://wshelloworld.quickstarts.as.jboss.org/", className = "org.jboss.as.quickstarts.wshelloworld.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://wshelloworld.quickstarts.as.jboss.org/", className = "org.jboss.as.quickstarts.wshelloworld.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod(operationName = "Hello")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://wshelloworld.quickstarts.as.jboss.org/", className = "org.jboss.as.quickstarts.wshelloworld.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://wshelloworld.quickstarts.as.jboss.org/", className = "org.jboss.as.quickstarts.wshelloworld.HelloResponse")
    public void hello();

}
